### ISSUE TITLE
Some thoughts on the class

### ISSUE THREAD

**Issue by t1gor** [plasticbrain/PHP-Flash-Messages#2]
Hi, Mike!

Great job on the Messages class, but I have several thoughts I would like to express:

1) It would be super cool if you would add several methods to customize the layout of the messages. Please see below for example:

```php
public function setBefore($newBefore = '')
{
	$this->msgBefore = $newBefore;
	return $this;
}

public function setAfter($newAfter = '')
{
	$this->msgAfter = $newAfter;
	return $this;
}

public function setClass($newClass = 'messages')
{
	$this->msgClass = $newClass;
	return $this;
}

public function setWrapper($newWrapper)
{
	$this->msgWrapper = $newWrapper;
	return $this;
}
```

2) Setting message types to constants would be super cool:
```php
const TYPE_SUCCESS = 'c';
const TYPE_ERROR   = 'e';
const TYPE_WARNING = 'w';
const TYPE_INFO    = 'i';
const TYPE_DEFAULT = 'i';
```

3) Message type in the add() method should go as the last parameter, so that you could set the message with no type specified, e.g. default type:
```php
public function add($message, $type = self::TYPE_DEFAULT, $redirect_to=null) {
```

Those changes would make the configuration and usage event easier and awesome. For example the setup to use [Twitter Bootstrap Alerts](http://getbootstrap.com/components/#alerts) would look smth like this:
```php
$messages = new Messages();
$messages->setBefore()
	->setAfter()
	->setClass('alert')
	->setWrapper('
		<div class="alert %s-%s alert-dismissable">
			<button type="button" class="close" data-dismiss="alert" aria-hidden="true">&times;</button>
			%s
		</div>');
```

Hope you will find my advise useful and thanks again for the class!

Igor

**Comment by t1gor** [comment]
@plasticbrain, the idea was to generally add the possibility to do that, but not to implement any specific template for Twitter Bootstrap. Anyhow, if you would like to do that, I would suggest adding a method like that:

````php
public function setBootstrapLayout() {
    return $this
        ->setBefore()
        ->setAfter()
        ->setClass('alert')
        ->setWrapper('
            <div class="alert %s-%s alert-dismissable">
                <button type="button" class="close" data-dismiss="alert" aria-hidden="true">&times;    </button>
                %s
            </div>');
}
```

and to use it, you would simply enable the one like this:

````php
$messages = new Messages();
$messages->setBootstrapLayout();
$messages->add("Some message");
...
````

Hope this helps! :)

**Comment by plasticbrain** [comment]
@t1gor -- thank you for your feedback and recommendations. I've finally found the time to properly update this class, and in doing so I believe I included most if not all of your requests.
